#!/usr/bin/env bash
clear
Black='\e[1;30m'       # Black
Red='\e[1;31m'         # Red
Green='\e[1;32m'       # Green
Yellow='\e[1;33m'      # Yellow
Blue='\e[1;34m'        # Blue
Purple='\e[1;35m'      # Purple
Cyan='\e[1;36m'        # Cyan
White='\e[1;37m'       # White
echo
echo -e "
      ────╔══╗╔╗──────────────╔══╗╔╗─────
      ────║╔╗║║║──────────────║╔╗║║║─────
      ╔══╗║╚╝║║║╔╗╔══╗╔══╗╔╗╔╗║╚╝║║║─╔══╗
      ║╔╗║║╔═╝║╚╝╝║══╣║╔╗║║╚╝║║╔═╝║║─║║═╣
      ║╔╗║║║──║╔╗╗─══║║╔╗║║║║║║║──║╚╗║║═╣
      ╚╝╚╝╚╝──╚╝╚╝╚══╝╚╝╚╝╚╩╩╝╚╝──╚═╝╚══╝"
echo -e "
${Red}=======${Yellow} [ List Apk ]${Red} =>${White}"
echo
echo -e "
${Red} [1]${Blue} apk BluetoothChat
${Red} [2]${Blue} apk CubeLiveWallpaper
${Red} [3]${Blue} apk Launcher
${Red} [4]${Blue} apk NotePad
${Red} [5]${Blue} apk WiFiDirectServiceDiscovery
${Red} [6]${Blue} apk Sdkmanager
${Red} [7] Exit"
echo
CUR_PATH=`pwd`
echo -n -e "${Cyan} Masukan nomor: ${White}"
read nomor

if [ $nomor = "1" ];
then
  cp -rf ${CUR_PATH}/assets/BluetoothChat ${CUR_PATH}
  cd ${CUR_PATH}/BluetoothChat
  bash ${CUR_PATH}/.build

elif [ $nomor = "2" ];
then
  cp -rf ${CUR_PATH}/assets/CubeLiveWallpaper ${CUR_PATH}
  cd ${CUR_PATH}/CubeLiveWallpaper
  bash ${CUR_PATH}/.build

elif [ $nomor = "3" ];
then
  cp -rf ${CUR_PATH}/assets/Home ${CUR_PATH}
  cd ${CUR_PATH}/Home
  bash ${CUR_PATH}/.build

elif [ $nomor = "4" ];
then
  cp -rf ${CUR_PATH}/assets/NotePad ${CUR_PATH}
  cd ${CUR_PATH}/NotePad
  bash ${CUR_PATH}/.build

elif [ $nomor = "5" ];
then
  cp -rf ${CUR_PATH}/assets/WiFiDirectServiceDiscovery ${CUR_PATH}
  cd ${CUR_PATH}/WiFiDirectServiceDiscovery
  bash ${CUR_PATH}/.build

elif [ $nomor = "6" ];
then
  cp -rf ${CUR_PATH}/assets/sdkmanager ${CUR_PATH}
  cd ${CUR_PATH}/sdkmanager
  bash ${CUR_PATH}/.build

elif [ $nomor = "7" ];
then
  exit

else
clear
echo -e "${Red} pilihan ga ada"
fi
